### PR TITLE
Add flow typings

### PR DESCRIPTION
**Pull request by RedBulli**
Type safety is important at this scale.

I left some flow typing practise for the next enthusiastic typer: adding flow types to our redux store and the react-di.

### CODE REVIEW

**Comment by ngergo6** [comment]
Is there a way to install Flow typings from npm like you can in case of TypeScript? Would be cool to integrate it into the build process.

**Comment by RedBulli** [comment]
Yes there is https://github.com/flowtype/flow-typed which I used to pull the definitions. Not including them in the repo might be a good idea.

**Comment by RedBulli** [comment]
Could we actually use both TypeScript and Flow? That would certainly make things more complicated.

**Comment by ngergo6** [comment]
I'm not sure they are compatible in the same file but we could use them in different parts of the application. TypeScript has pretty good support for React components with .tsx extension, maybe we could integrated that too somehow :smiley:

**Pull request closed without merging**
